#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

layout(binding = 0) buffer InOut {
    uint result[];
};

void main() {
    result[gl_GlobalInvocationID.x] = gl_GlobalInvocationID.x;

    //uint x = (gl_GlobalInvocationID.x % 512) / 16;
    //uint y = (gl_GlobalInvocationID.x / 512) / 16;

    //result[gl_GlobalInvocationID.x] = 64*((x+y) & 1) + 16*((x+y) & 7);
}
